In [2]:
import pandas as pd
import numpy as np

## Data Cleaning Extras
#### Goals for this step
- Remove null bathrooms and bedrooms from data set

In [3]:
df = pd.read_pickle("C:/Users/Admin/Documents/ironhack/AirBnB_data/airbnb_listings_countries.pkl")

In [4]:
df

,Listing ID,Name,Host ID,Host Name,Host Response Rate,Host Is Superhost,Host total listings count,Country,latitude,longitude,...,Last Review Date,Review Scores Rating,Review Scores Accuracy,Review Scores Cleanliness,Review Scores Checkin,Review Scores Communication,Review Scores Location,Review Scores Value,Reviews per month,Amenity_Count
0,5534229,A 2 Passi da San Pietro,28697142,Veronica,100.0,False,5.0,Italy,41.895878,12.454430,...,2015-08-29,90.0,9.0,10.0,8.0,8.0,9.0,9.0,0.08,11
1,5903406,cosy small apartment,1853799,Veronika,88.0,False,2.0,Austria,48.246033,16.340743,...,2017-09-09,87.0,9.0,10.0,10.0,10.0,10.0,8.0,0.27,12
2,5203533,Rummelig lejl i hjertet af KBH,24801534,Marianne,100.0,False,1.0,Denmark,55.681579,12.562770,...,2016-07-26,100.0,10.0,10.0,10.0,10.0,10.0,10.0,0.28,8
3,8858475,Modern; spacious and warm; with its own balcony,3000397,Lasse,100.0,True,1.0,Denmark,55.708413,12.596737,...,2017-05-07,100.0,10.0,10.0,10.0,10.0,9.0,10.0,0.79,23
4,4215511,Nice room; Bohemian Cph; Nï¿½rrebro,126020,Lea,100.0,True,2.0,Denmark,55.687506,12.558365,...,2017-05-08,94.0,10.0,10.0,9.0,10.0,10.0,10.0,1.40,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379050,20810636,Modern Apartment in a Great Location!,149230231,Ricardo And Jessi,100.0,False,1.0,United States,42.351047,-71.131691,...,2017-09-24,100.0,10.0,10.0,10.0,10.0,10.0,10.0,6.00,24
379051,9563852,CHARMING STUDIO IN BARBES; NEAR MONTMARTRE,17267346,Laura,90.0,False,1.0,France,48.893828,2.351774,...,2017-03-10,96.0,10.0,9.0,10.0,10.0,9.0,9.0,1.42,9
379052,5841088,Bright 1Bedroom Apartment & Rooftop,7260061,Diana,100.0,False,1.0,Australia,-33.891942,151.276991,...,2017-01-01,97.0,10.0,9.0,9.0,10.0,10.0,9.0,0.29,16
379053,12157261,Chambre douillette; appart lumineux; rue St-Jean,65286315,Catherine,50.0,False,1.0,Canada,46.808525,-71.222046,...,2017-06-18,94.0,9.0,9.0,10.0,10.0,10.0,9.0,2.82,13
379054,11225183,Hollywood Pool Home w/ Pool House!!,42821904,Bobby,100.0,False,3.0,United States,34.162633,-118.363057,...,2017-01-23,90.0,10.0,9.0,10.0,10.0,10.0,10.0,0.38,21

We will remove rows where there are null values for bedrooms and bathrooms.

In [5]:
df = df[(~df["Bathrooms"].isna())]

In [6]:
df

,Listing ID,Name,Host ID,Host Name,Host Response Rate,Host Is Superhost,Host total listings count,Country,latitude,longitude,...,Last Review Date,Review Scores Rating,Review Scores Accuracy,Review Scores Cleanliness,Review Scores Checkin,Review Scores Communication,Review Scores Location,Review Scores Value,Reviews per month,Amenity_Count
0,5534229,A 2 Passi da San Pietro,28697142,Veronica,100.0,False,5.0,Italy,41.895878,12.454430,...,2015-08-29,90.0,9.0,10.0,8.0,8.0,9.0,9.0,0.08,11
1,5903406,cosy small apartment,1853799,Veronika,88.0,False,2.0,Austria,48.246033,16.340743,...,2017-09-09,87.0,9.0,10.0,10.0,10.0,10.0,8.0,0.27,12
2,5203533,Rummelig lejl i hjertet af KBH,24801534,Marianne,100.0,False,1.0,Denmark,55.681579,12.562770,...,2016-07-26,100.0,10.0,10.0,10.0,10.0,10.0,10.0,0.28,8
3,8858475,Modern; spacious and warm; with its own balcony,3000397,Lasse,100.0,True,1.0,Denmark,55.708413,12.596737,...,2017-05-07,100.0,10.0,10.0,10.0,10.0,9.0,10.0,0.79,23
4,4215511,Nice room; Bohemian Cph; Nï¿½rrebro,126020,Lea,100.0,True,2.0,Denmark,55.687506,12.558365,...,2017-05-08,94.0,10.0,10.0,9.0,10.0,10.0,10.0,1.40,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379050,20810636,Modern Apartment in a Great Location!,149230231,Ricardo And Jessi,100.0,False,1.0,United States,42.351047,-71.131691,...,2017-09-24,100.0,10.0,10.0,10.0,10.0,10.0,10.0,6.00,24
379051,9563852,CHARMING STUDIO IN BARBES; NEAR MONTMARTRE,17267346,Laura,90.0,False,1.0,France,48.893828,2.351774,...,2017-03-10,96.0,10.0,9.0,10.0,10.0,9.0,9.0,1.42,9
379052,5841088,Bright 1Bedroom Apartment & Rooftop,7260061,Diana,100.0,False,1.0,Australia,-33.891942,151.276991,...,2017-01-01,97.0,10.0,9.0,9.0,10.0,10.0,9.0,0.29,16
379053,12157261,Chambre douillette; appart lumineux; rue St-Jean,65286315,Catherine,50.0,False,1.0,Canada,46.808525,-71.222046,...,2017-06-18,94.0,9.0,9.0,10.0,10.0,10.0,9.0,2.82,13
379054,11225183,Hollywood Pool Home w/ Pool House!!,42821904,Bobby,100.0,False,3.0,United States,34.162633,-118.363057,...,2017-01-23,90.0,10.0,9.0,10.0,10.0,10.0,10.0,0.38,21

In [7]:
df = df[(~df["Bedrooms"].isna())]

In [8]:
df

,Listing ID,Name,Host ID,Host Name,Host Response Rate,Host Is Superhost,Host total listings count,Country,latitude,longitude,...,Last Review Date,Review Scores Rating,Review Scores Accuracy,Review Scores Cleanliness,Review Scores Checkin,Review Scores Communication,Review Scores Location,Review Scores Value,Reviews per month,Amenity_Count
0,5534229,A 2 Passi da San Pietro,28697142,Veronica,100.0,False,5.0,Italy,41.895878,12.454430,...,2015-08-29,90.0,9.0,10.0,8.0,8.0,9.0,9.0,0.08,11
1,5903406,cosy small apartment,1853799,Veronika,88.0,False,2.0,Austria,48.246033,16.340743,...,2017-09-09,87.0,9.0,10.0,10.0,10.0,10.0,8.0,0.27,12
2,5203533,Rummelig lejl i hjertet af KBH,24801534,Marianne,100.0,False,1.0,Denmark,55.681579,12.562770,...,2016-07-26,100.0,10.0,10.0,10.0,10.0,10.0,10.0,0.28,8
3,8858475,Modern; spacious and warm; with its own balcony,3000397,Lasse,100.0,True,1.0,Denmark,55.708413,12.596737,...,2017-05-07,100.0,10.0,10.0,10.0,10.0,9.0,10.0,0.79,23
4,4215511,Nice room; Bohemian Cph; Nï¿½rrebro,126020,Lea,100.0,True,2.0,Denmark,55.687506,12.558365,...,2017-05-08,94.0,10.0,10.0,9.0,10.0,10.0,10.0,1.40,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379050,20810636,Modern Apartment in a Great Location!,149230231,Ricardo And Jessi,100.0,False,1.0,United States,42.351047,-71.131691,...,2017-09-24,100.0,10.0,10.0,10.0,10.0,10.0,10.0,6.00,24
379051,9563852,CHARMING STUDIO IN BARBES; NEAR MONTMARTRE,17267346,Laura,90.0,False,1.0,France,48.893828,2.351774,...,2017-03-10,96.0,10.0,9.0,10.0,10.0,9.0,9.0,1.42,9
379052,5841088,Bright 1Bedroom Apartment & Rooftop,7260061,Diana,100.0,False,1.0,Australia,-33.891942,151.276991,...,2017-01-01,97.0,10.0,9.0,9.0,10.0,10.0,9.0,0.29,16
379053,12157261,Chambre douillette; appart lumineux; rue St-Jean,65286315,Catherine,50.0,False,1.0,Canada,46.808525,-71.222046,...,2017-06-18,94.0,9.0,9.0,10.0,10.0,10.0,9.0,2.82,13
379054,11225183,Hollywood Pool Home w/ Pool House!!,42821904,Bobby,100.0,False,3.0,United States,34.162633,-118.363057,...,2017-01-23,90.0,10.0,9.0,10.0,10.0,10.0,10.0,0.38,21

In [9]:
df = df.reset_index(drop=True)

In [10]:
df

,Listing ID,Name,Host ID,Host Name,Host Response Rate,Host Is Superhost,Host total listings count,Country,latitude,longitude,...,Last Review Date,Review Scores Rating,Review Scores Accuracy,Review Scores Cleanliness,Review Scores Checkin,Review Scores Communication,Review Scores Location,Review Scores Value,Reviews per month,Amenity_Count
0,5534229,A 2 Passi da San Pietro,28697142,Veronica,100.0,False,5.0,Italy,41.895878,12.454430,...,2015-08-29,90.0,9.0,10.0,8.0,8.0,9.0,9.0,0.08,11
1,5903406,cosy small apartment,1853799,Veronika,88.0,False,2.0,Austria,48.246033,16.340743,...,2017-09-09,87.0,9.0,10.0,10.0,10.0,10.0,8.0,0.27,12
2,5203533,Rummelig lejl i hjertet af KBH,24801534,Marianne,100.0,False,1.0,Denmark,55.681579,12.562770,...,2016-07-26,100.0,10.0,10.0,10.0,10.0,10.0,10.0,0.28,8
3,8858475,Modern; spacious and warm; with its own balcony,3000397,Lasse,100.0,True,1.0,Denmark,55.708413,12.596737,...,2017-05-07,100.0,10.0,10.0,10.0,10.0,9.0,10.0,0.79,23
4,4215511,Nice room; Bohemian Cph; Nï¿½rrebro,126020,Lea,100.0,True,2.0,Denmark,55.687506,12.558365,...,2017-05-08,94.0,10.0,10.0,9.0,10.0,10.0,10.0,1.40,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379050,20810636,Modern Apartment in a Great Location!,149230231,Ricardo And Jessi,100.0,False,1.0,United States,42.351047,-71.131691,...,2017-09-24,100.0,10.0,10.0,10.0,10.0,10.0,10.0,6.00,24
379051,9563852,CHARMING STUDIO IN BARBES; NEAR MONTMARTRE,17267346,Laura,90.0,False,1.0,France,48.893828,2.351774,...,2017-03-10,96.0,10.0,9.0,10.0,10.0,9.0,9.0,1.42,9
379052,5841088,Bright 1Bedroom Apartment & Rooftop,7260061,Diana,100.0,False,1.0,Australia,-33.891942,151.276991,...,2017-01-01,97.0,10.0,9.0,9.0,10.0,10.0,9.0,0.29,16
379053,12157261,Chambre douillette; appart lumineux; rue St-Jean,65286315,Catherine,50.0,False,1.0,Canada,46.808525,-71.222046,...,2017-06-18,94.0,9.0,9.0,10.0,10.0,10.0,9.0,2.82,13
379054,11225183,Hollywood Pool Home w/ Pool House!!,42821904,Bobby,100.0,False,3.0,United States,34.162633,-118.363057,...,2017-01-23,90.0,10.0,9.0,10.0,10.0,10.0,10.0,0.38,21

In [11]:
# df.to_pickle("C:/Users/Admin/Documents/ironhack/AirBnB_data/airbnb_listings_countries.pkl")

We will do the same for the US dataframe.

In [12]:
df_usa = pd.read_pickle("C:/Users/Admin/Documents/ironhack/AirBnB_data/airbnb_listings_usa.pkl")

In [13]:
df_usa

,Listing ID,Name,Host ID,Host Name,Host Response Rate,Host Is Superhost,Host total listings count,Street,City,Neighbourhood cleansed,...,Last Review Date,Review Scores Rating,Review Scores Accuracy,Review Scores Cleanliness,Review Scores Checkin,Review Scores Communication,Review Scores Location,Review Scores Value,Reviews per month,Amenity_Count
0,4581256,Beacon hill small bedroom (__),20448703,Jennifer,94.0,False,5.0,S Morgan St| ___| WA 98108| United States,___,Mid-Beacon Hill,...,2015-11-03,89.0,10.0,10.0,9.0,9.0,9.0,9.0,2.10,12
1,3967592,Minutes to Boston-Near Beach 71-3,20551003,May,100.0,False,17.0,___| MA| United States,___,East Boston,...,2017-09-18,95.0,10.0,10.0,9.0,9.0,9.0,10.0,0.95,17
2,12205354,Artsy apartment near Moscone Center,65392037,Alex,100.0,False,1.0,___| CA| United States,San Francisco,South of Market,...,2017-09-25,92.0,9.0,9.0,10.0,10.0,9.0,9.0,5.22,23
3,3230382,Large master bedroom & covered patio; __________,15878447,Betty,100.0,True,9.0,___| CA 91755| United States,Los Angeles,Monterey Park,...,2016-12-28,95.0,10.0,9.0,9.0,10.0,10.0,9.0,1.11,14
4,10491563,___downtown____soma__loft_____,48920457,Margarita,100.0,False,1.0,___| CA| United States,San Francisco,Financial District,...,2016-06-15,100.0,10.0,10.0,10.0,10.0,10.0,10.0,0.24,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108306,13764162,Beautiful Home in Encino. 15 Min from Everything!,15055856,Matthew,NaN,False,1.0,CA| CA| United States,Los Angeles,Encino,...,2016-08-02,100.0,10.0,10.0,10.0,10.0,10.0,10.0,0.21,25
108307,8867269,Studio apartment in west campus,25507803,Marle,NaN,False,1.0,Leon Street| Austin| TX| United States,NaN,78705,...,2016-11-12,90.0,10.0,9.0,10.0,10.0,9.0,10.0,0.30,9
108308,19824378,Private 2 Bedroom Luxury Townhouse; Chestnut Hill,133582807,Taylor,100.0,False,1.0,MA| MA| United States,NaN,West Roxbury,...,2017-10-01,100.0,10.0,10.0,10.0,10.0,10.0,10.0,3.95,49
108309,20810636,Modern Apartment in a Great Location!,149230231,Ricardo And Jessi,100.0,False,1.0,MA| MA| United States,NaN,Allston,...,2017-09-24,100.0,10.0,10.0,10.0,10.0,10.0,10.0,6.00,24
108310,11225183,Hollywood Pool Home w/ Pool House!!,42821904,Bobby,100.0,False,3.0,CA| CA| United States,Los Angeles,North Hollywood,...,2017-01-23,90.0,10.0,9.0,10.0,10.0,10.0,10.0,0.38,21

In [19]:
df_usa = df_usa[(~df_usa["Bathrooms"].isna())]

In [20]:
df_usa

,Listing ID,Name,Host ID,Host Name,Host Response Rate,Host Is Superhost,Host total listings count,Street,City,Neighbourhood cleansed,...,Last Review Date,Review Scores Rating,Review Scores Accuracy,Review Scores Cleanliness,Review Scores Checkin,Review Scores Communication,Review Scores Location,Review Scores Value,Reviews per month,Amenity_Count
0,4581256,Beacon hill small bedroom (__),20448703,Jennifer,94.0,False,5.0,S Morgan St| ___| WA 98108| United States,___,Mid-Beacon Hill,...,2015-11-03,89.0,10.0,10.0,9.0,9.0,9.0,9.0,2.10,12
1,3967592,Minutes to Boston-Near Beach 71-3,20551003,May,100.0,False,17.0,___| MA| United States,___,East Boston,...,2017-09-18,95.0,10.0,10.0,9.0,9.0,9.0,10.0,0.95,17
2,12205354,Artsy apartment near Moscone Center,65392037,Alex,100.0,False,1.0,___| CA| United States,San Francisco,South of Market,...,2017-09-25,92.0,9.0,9.0,10.0,10.0,9.0,9.0,5.22,23
3,3230382,Large master bedroom & covered patio; __________,15878447,Betty,100.0,True,9.0,___| CA 91755| United States,Los Angeles,Monterey Park,...,2016-12-28,95.0,10.0,9.0,9.0,10.0,10.0,9.0,1.11,14
4,10491563,___downtown____soma__loft_____,48920457,Margarita,100.0,False,1.0,___| CA| United States,San Francisco,Financial District,...,2016-06-15,100.0,10.0,10.0,10.0,10.0,10.0,10.0,0.24,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108306,13764162,Beautiful Home in Encino. 15 Min from Everything!,15055856,Matthew,NaN,False,1.0,CA| CA| United States,Los Angeles,Encino,...,2016-08-02,100.0,10.0,10.0,10.0,10.0,10.0,10.0,0.21,25
108307,8867269,Studio apartment in west campus,25507803,Marle,NaN,False,1.0,Leon Street| Austin| TX| United States,NaN,78705,...,2016-11-12,90.0,10.0,9.0,10.0,10.0,9.0,10.0,0.30,9
108308,19824378,Private 2 Bedroom Luxury Townhouse; Chestnut Hill,133582807,Taylor,100.0,False,1.0,MA| MA| United States,NaN,West Roxbury,...,2017-10-01,100.0,10.0,10.0,10.0,10.0,10.0,10.0,3.95,49
108309,20810636,Modern Apartment in a Great Location!,149230231,Ricardo And Jessi,100.0,False,1.0,MA| MA| United States,NaN,Allston,...,2017-09-24,100.0,10.0,10.0,10.0,10.0,10.0,10.0,6.00,24
108310,11225183,Hollywood Pool Home w/ Pool House!!,42821904,Bobby,100.0,False,3.0,CA| CA| United States,Los Angeles,North Hollywood,...,2017-01-23,90.0,10.0,9.0,10.0,10.0,10.0,10.0,0.38,21

In [21]:
df_usa = df_usa[(~df_usa["Bedrooms"].isna())]

In [22]:
df_usa

,Listing ID,Name,Host ID,Host Name,Host Response Rate,Host Is Superhost,Host total listings count,Street,City,Neighbourhood cleansed,...,Last Review Date,Review Scores Rating,Review Scores Accuracy,Review Scores Cleanliness,Review Scores Checkin,Review Scores Communication,Review Scores Location,Review Scores Value,Reviews per month,Amenity_Count
0,4581256,Beacon hill small bedroom (__),20448703,Jennifer,94.0,False,5.0,S Morgan St| ___| WA 98108| United States,___,Mid-Beacon Hill,...,2015-11-03,89.0,10.0,10.0,9.0,9.0,9.0,9.0,2.10,12
1,3967592,Minutes to Boston-Near Beach 71-3,20551003,May,100.0,False,17.0,___| MA| United States,___,East Boston,...,2017-09-18,95.0,10.0,10.0,9.0,9.0,9.0,10.0,0.95,17
2,12205354,Artsy apartment near Moscone Center,65392037,Alex,100.0,False,1.0,___| CA| United States,San Francisco,South of Market,...,2017-09-25,92.0,9.0,9.0,10.0,10.0,9.0,9.0,5.22,23
3,3230382,Large master bedroom & covered patio; __________,15878447,Betty,100.0,True,9.0,___| CA 91755| United States,Los Angeles,Monterey Park,...,2016-12-28,95.0,10.0,9.0,9.0,10.0,10.0,9.0,1.11,14
4,10491563,___downtown____soma__loft_____,48920457,Margarita,100.0,False,1.0,___| CA| United States,San Francisco,Financial District,...,2016-06-15,100.0,10.0,10.0,10.0,10.0,10.0,10.0,0.24,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108306,13764162,Beautiful Home in Encino. 15 Min from Everything!,15055856,Matthew,NaN,False,1.0,CA| CA| United States,Los Angeles,Encino,...,2016-08-02,100.0,10.0,10.0,10.0,10.0,10.0,10.0,0.21,25
108307,8867269,Studio apartment in west campus,25507803,Marle,NaN,False,1.0,Leon Street| Austin| TX| United States,NaN,78705,...,2016-11-12,90.0,10.0,9.0,10.0,10.0,9.0,10.0,0.30,9
108308,19824378,Private 2 Bedroom Luxury Townhouse; Chestnut Hill,133582807,Taylor,100.0,False,1.0,MA| MA| United States,NaN,West Roxbury,...,2017-10-01,100.0,10.0,10.0,10.0,10.0,10.0,10.0,3.95,49
108309,20810636,Modern Apartment in a Great Location!,149230231,Ricardo And Jessi,100.0,False,1.0,MA| MA| United States,NaN,Allston,...,2017-09-24,100.0,10.0,10.0,10.0,10.0,10.0,10.0,6.00,24
108310,11225183,Hollywood Pool Home w/ Pool House!!,42821904,Bobby,100.0,False,3.0,CA| CA| United States,Los Angeles,North Hollywood,...,2017-01-23,90.0,10.0,9.0,10.0,10.0,10.0,10.0,0.38,21

In [23]:
# df_usa.to_pickle("C:/Users/Admin/Documents/ironhack/AirBnB_data/airbnb_listings_usa.pkl")